-  name: copy grafana repo file
   ansible.builtin.template:
      src: grafana.repo
      dest: /etc/yum.repos.d/grafana.repo

-  name: Install grafana
   ansible.builtin.dnf:
      name: grafana
      state: installed

-  name: Start Grafana
   ansible.builtin.systemd_service:
      name: grafana-server
      state: restarted
      enabled: true
      daemon-reload: true


