- name: Setting up prompt for elk
  ansible.builtin.shell: set-prompt Grafana

-  name: copy grafana repo file
   ansible.builtin.template:
      src: grafana.repo
      dest: /etc/yum.repos.d/grafana.repo

-  name: Install grafana
   ansible.builtin.dnf:
      name: grafana
      state: installed

- name: copy datasource file
  ansible.builtin.template:
    src: dash-datasource.yml
    dest: /etc/grafana/provisioning/datasources/prom.yml

- name: copy dashboard template
  ansible.builtin.template:
    src: sample-dash.json
    dest: /tmp/sample-dash.json

- name: Create a folder
  community.grafana.grafana_folder:
    url: "http://grafana.shujadevops.shop:3000"
    grafana_user: "admin"
    grafana_password: "admin123"
    title: "ProjectDashboard Full"
    state: present

- name: Import Grafana dashboard foo
  community.grafana.grafana_dashboard:
    grafana_url: http://grafana.shujadevops.shop:3000
    grafana_user: "admin"
    grafana_password: "admin123"
    folder: ProjectDashboard Full
    state: present
    commit_message: Updated by ansible
    overwrite: true
    path: /tmp/sample-dash.json

-  name: Start Grafana
   ansible.builtin.systemd_service:
      name: grafana-server
      state: restarted
      enabled: true
      daemon-reload: true

