- name: Setting up prompt for elk
  ansible.builtin.shell: set-prompt elk

- name: copy elastic repo file
  ansible.builtin.template:
    src: elastic.repo
    dest: /etc/yum.repos.d/elastic.repo

- name: Install elasticsearch
  ansible.builtin.dnf:
    name: elasticsearch
    state: installed

- name: start elastic search
  ansible.builtin.systemd_service:
    name: elasticsearch
    state: started
    enabled: yes
    daemon_reload: yes

- name: Install Kibana
  ansible.builtin.dnf:
    name: kibana
    state: installed

- name: Update kibana config file server port
  ansible.builtin.lineinfile:
    path: /etc/kibana/kibana.yml
    regexp: '^#server.port: 5601'
    line: "server.port: 5601"

- name: Update kibana config file server host
  ansible.builtin.lineinfile:
    path: /etc/kibana/kibana.yml
    regexp: '^#server.host: localhost'
    line: "server.port: 0.0.0.0"

- name: start kibana
  ansible.builtin.systemd_service:
    name: kibana
    state: restarted
    enabled: yes

