format_version: 10
pipelines:
 Prometheus:
  group: Terraform
  label_template: ${COUNT}
  lock_behavior: none
  display_order: -1
  materials:
    git-3caedef:
      git: https://github.com/s-devops-i2/tools-automation-code.git
      shallow_clone: false
      auto_update: true
      branch: main
  stages:
    - DEV:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: manual
          allow_only_on_success: false
        jobs:
          Prometheus:
            timeout: 0
            tasks:
              - exec: {command: terraform, arguments: ["init"],run_if: passed}
              - exec: {command: terraform, arguments: ["apply", "-auto-approve"],run_if: passed}



