- name: Download and Install prometheus
  ansible.builtin.unarchive:
    src: https://github.com/prometheus/prometheus/releases/download/v{{ version }}/prometheus-{{ version}}.linux-amd64.tar.gz
    dest: /opt
    remote_src: yes
    owner: bin

- name: Copy Prometheus Service file
  ansible.builtin.template:
    src: prometheus.service
    dest: /etc/systemd/system/prometheus.service

- name: Copy Prometheus config file
  ansible.builtin.template:
    src: prometheus.yml
    dest: /opt/prometheus-2.53.3.linux-amd64


- name: Start Prometheus
  ansible.builtin.systemd_service:
    state: restarted
    name: prometheus
    enabled: true
    daemon_reload: true

