- name: Download and Install prometheus
  ansible.builtin.unarchive:
    src: https://github.com/prometheus/prometheus/releases/download/v{{ version }}/prometheus-{{ version}}.linux-amd64.tar.gz
    dest: /opt
    remote_src: yes

- name: Copy Prometheus Service file
  ansible.builtin.template:
    src: prometheus.service
    dest: /etc/systemd/system/prometheus.service

- name: Start Prometheus
  ansible.builtin.systemd_service:
    state: restarted
    name: prometheus
    enabled: true
    daemon_reload: true

