# my global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

scrape_configs:
  - job_name: "ec2-nodes"
    ec2_sd_configs:
      - region: us-east-1
        port: 9100
        filters:
         - name: tag:monitor
           values: ["yes"]
    relabel_configs:
      - source_labels: [ __meta_ec2_tag_Name ]
        target_label: name
      - source_labels: [ __meta_ec2_tag_env ]
        target_label: env
